version: '3.8'

services:
  # app:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATA_REDIS_HOST=redis
  #     - SPRING_DATA_REDIS_PORT=6379
  #   depends_on:
  #     - redis
  #   networks:
  #     - rate-limiter-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge

volumes:
  redis-data: 